### ISSUE TITLE
refactor: Visit -> Moment, VisitLog -> Comment 도메인 명 마이그레이션

### ISSUE THREAD

**Issue by Junyoung-WON** [woowacourse-teams/2024-staccato#218]
### ✅ CheckList
- [ ] 도메인 명 변경
  - [x] xml
  - [ ] data
    - [x] SerialName 신경쓰기!
  - [ ] presentation
  - [x] domain
- [ ] 정상 동작 확인

**Comment by hxeyexn** [comment]
- #240 에서 이어서 작업
