### ISSUE TITLE
refactor: comments API URI 수정

### ISSUE THREAD

**Issue by linirini** [woowacourse-teams/2024-staccato#544]
## 🤮 As Is
> 리팩터링하고자 하는 파트와 이유를 구체적으로 설명해주세요.
- 댓글 조회 API의 URI를 수정하고자 합니다.
- `PUT, DELETE /comments?commentId={commentId}` -> `PUT, DELETE /comments/{commentId}`
- 필터링이 아닌, 특정 자원을 식별하기 위함이므로 Query String보다는 path variable이 적합하다고 판단하여 리팩토링하고자 합니다.
## 🤩 To Be
> 리팩터링 방향을 구체적으로 공유해주세요.
- `PUT, DELETE /comments?commentId={commentId}` -> `PUT, DELETE /comments/{commentId}`
- `/v2/comments/{commentId}`로 버저닝하여 안드로이드 개발 전까지 지원 예정입니다.
    - @Junyoung-WON 추후 확인하고, 반영 부탁드립니다!
- 운영 배포 시 강제 업데이트로 배포할 것인지, 아닌지에 따라 버저닝을 유지할 지 결정할 것 같습니다.

## 😇 이때까지 끝낼게요!
> 리팩터링 완료 예상 날짜를 작성해주세요. 신중하게 생각해요!

11/10까지 마무리 예정입니다. (이슈 컨펌 날짜 생각하여 넉넉하게 잡았어요)

## 🙇‍♀️이슈 확인했어요:)
> 팀원에게 이슈 확인을 부탁해요!
- [x] @hxeyexn 
- [x] @s6m1n 
- [ ] @Junyoung-WON 
- [x] @BurningFalls 
- [x] @Ho-Tea

**Comment by Ho-Tea** [comment]
## 궁금한 부분
기존에 존재하던 쿼리파라미터 형태에서 PathVariable형태로 변경하면서 버저닝이 아닌 아래와 같이 구성할 수 있을 것 같은데,
버저닝을 도입하신 이유가 궁금합니다.

``` java
    @GetMapping
    public ResponseEntity<CommentResponses> readCommentsByMomentId(
            @LoginMember Member member,
            @RequestParam @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId
    ) {
        CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
        return ResponseEntity.ok().body(commentResponses);
    }

    @GetMapping(path = "/{momentId}")
    public ResponseEntity<CommentResponses> readCommentsByMomentIdPathVariable(
            @LoginMember Member member,
            @PathVariable @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId) {
        CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
        return ResponseEntity.ok().body(commentResponses);
    }

```

**Comment by linirini** [comment]
> ## 궁금한 부분
> 기존에 존재하던 쿼리파라미터 형태에서 PathVariable형태로 변경하면서 버저닝이 아닌 아래와 같이 구성할 수 있을 것 같은데, 버저닝을 도입하신 이유가 궁금합니다.
> 
> ```java
>     @GetMapping
>     public ResponseEntity<CommentResponses> readCommentsByMomentId(
>             @LoginMember Member member,
>             @RequestParam @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId
>     ) {
>         CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
>         return ResponseEntity.ok().body(commentResponses);
>     }
> 
>     @GetMapping(path = "/{momentId}")
>     public ResponseEntity<CommentResponses> readCommentsByMomentIdPathVariable(
>             @LoginMember Member member,
>             @PathVariable @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId) {
>         CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
>         return ResponseEntity.ok().body(commentResponses);
>     }
> ```

동일한 목적의 API가 2가지가 존재하는 것이므로, 명시해줄 필요가 있다고 생각했습니다. API를 사용하는 클라이언트 측에서도 어떤 API를 대신할 새로운 버전임을 분명하게 인지하고 다른 목적으로 API를 혼용하는 문제를 방지할 수 있다고 생각했습니다.
